[package]
name = "chirp8-c64"
version = "0.1.0"
authors = ["ÉRDI Gergő <gergo@erdi.hu>"]

[lib]
crate-type = ["rlib"]

[profile.release]
panic = "abort"

[dependencies]
chirp8-engine = { path="chirp8-engine" }
